// Diesel Rates master — the diesel price per state per fortnight behind the
// Tanker Rate Master (migration 058). From here the fortnight's ₹/km rows can
// be generated by purchase's escalation formula (previous rate + Δdiesel ÷
// mileage): the screen always previews first and writes only on Confirm.
import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import toast from 'react-hot-toast';
import { Plus, Pencil, Trash2, X, Download, Calculator } from 'lucide-react';
import {
  getDieselRateMatrix, createDieselRate, updateDieselRate, deleteDieselRate,
  previewRatesFromDiesel, generateRatesFromDiesel, downloadRateAnnexure,
} from '../../api';
import { Modal } from '../../components/MasterTable';
import { useAuth } from '../../hooks/useAuth';
import { hasRole, isReadOnly } from '../../utils/roles';
import { fmtDate } from '../../utils/date';

const STATES = ['Andhra Pradesh', 'Tamil Nadu', 'Karnataka', 'Telangana'];
const nf = (v, d = 2) => v == null ? '—' : Number(v).toLocaleString('en-IN', { minimumFractionDigits: d, maximumFractionDigits: d });
const sign = v => v == null ? '—' : (v > 0 ? '+' : '') + nf(v);

// Fortnight → dates ('YYYY-MM' + '1' | '2').
const fnDates = (month, fortnight) => {
  if (!month) return null;
  const [y, m] = month.split('-').map(Number);
  const end = new Date(y, m, 0).getDate();
  return fortnight === '1'
    ? { from: `${month}-01`, to: `${month}-15` }
    : { from: `${month}-16`, to: `${month}-${String(end).padStart(2, '0')}` };
};
const todayMonth = () => new Date().toISOString().slice(0, 7);

export default function DieselRates() {
  const qc = useQueryClient();
  const { user } = useAuth();
  const canEdit = !isReadOnly(user) && (hasRole(user, 'admin') || user?.permissions?.masters === true);

  const [month, setMonth]         = useState(todayMonth());
  const [fortnight, setFortnight] = useState(new Date().getDate() > 15 ? '2' : '1');
  const [edit, setEdit]           = useState(null);   // { id?, state, price_per_litre, source }
  const [preview, setPreview]     = useState(null);   // generate-preview response
  const [replace, setReplace]     = useState(false);
  const period = fnDates(month, fortnight);

  const { data: matrix, isLoading } = useQuery({
    queryKey: ['diesel-rates', 'matrix'],
    queryFn: () => getDieselRateMatrix({ periods: 24 }).then(r => r.data),
  });
  const current = matrix?.periods?.find(p => p.effective_from === period?.from);

  const saveMut = useMutation({
    mutationFn: () => {
      const body = { ...edit, effective_from: period.from, effective_to: period.to };
      return edit.id ? updateDieselRate(edit.id, body) : createDieselRate(body);
    },
    onSuccess: () => { toast.success('Diesel price saved'); setEdit(null); qc.invalidateQueries({ queryKey: ['diesel-rates'] }); },
    onError: e => toast.error(e.response?.data?.error || e.message),
  });
  const delMut = useMutation({
    mutationFn: id => deleteDieselRate(id),
    onSuccess: () => { toast.success('Deleted'); qc.invalidateQueries({ queryKey: ['diesel-rates'] }); },
    onError: e => toast.error(e.response?.data?.error || e.message),
  });
  const previewMut = useMutation({
    mutationFn: () => previewRatesFromDiesel({ effective_from: period.from, effective_to: period.to }),
    onSuccess: r => { setPreview(r.data); setReplace(false); },
    onError: e => toast.error(e.response?.data?.error || e.message),
  });
  const genMut = useMutation({
    mutationFn: () => generateRatesFromDiesel({ effective_from: period.from, effective_to: period.to, replace }),
    onSuccess: r => {
      toast.success(`Tanker Rate Master: ${r.data.inserted} row(s) added${r.data.updated ? `, ${r.data.updated} replaced` : ''}${r.data.skipped ? `, ${r.data.skipped} skipped` : ''}`, { duration: 8000 });
      setPreview(null);
      qc.invalidateQueries({ queryKey: ['tanker-rates'] });
    },
    onError: e => toast.error(e.response?.data?.error || e.message),
  });

  const set = (k, v) => setEdit(f => ({ ...f, [k]: v }));

  return (
    <div className="p-4 space-y-4">
      <div className="flex flex-wrap items-end gap-3">
        <div>
          <h2 className="page-title">Diesel Rates</h2>
          <p className="text-xs" style={{ color: 'rgba(255,255,255,0.92)' }}>
            Diesel ₹/litre per state per fortnight — the basis of the Tanker Rate Master (rate = previous rate + Δdiesel ÷ mileage)
          </p>
        </div>
        <div className="flex-1" />
        <input type="month" className="input text-xs" value={month} onChange={e => setMonth(e.target.value)}/>
        <select className="input text-xs" value={fortnight} onChange={e => setFortnight(e.target.value)}>
          <option value="1">1st fortnight (1 – 15)</option>
          <option value="2">2nd fortnight (16 – month end)</option>
        </select>
        {period && (
          <button className="btn-secondary text-xs flex items-center gap-1.5" title="Rate annexure for this fortnight (needs Tanker Rate Master rows)"
                  onClick={() => downloadRateAnnexure(period.from).catch(e => toast.error(e.response?.status === 404 ? 'No Tanker Rate Master rows for this fortnight yet' : e.message))}>
            <Download size={13}/> Annexure
          </button>
        )}
        {canEdit && period && (
          <button className="btn-primary text-xs flex items-center gap-1.5" disabled={previewMut.isPending}
                  title="Carry the previous fortnight's rates forward by the diesel movement — preview first, nothing is saved until you confirm"
                  onClick={() => previewMut.mutate()}>
            <Calculator size={13}/> {previewMut.isPending ? 'Calculating…' : 'Generate rates from diesel'}
          </button>
        )}
      </div>

      {/* This fortnight: one row per state */}
      {period && (
        <div className="card p-4 space-y-2">
          <div className="font-semibold text-sm">Diesel prices {fmtDate(period.from)} → {fmtDate(period.to)}</div>
          <table className="w-full text-xs">
            <thead><tr className="text-left text-gray-600 bg-blue-50">
              <th className="px-3 py-2">State</th><th className="px-3 py-2 text-right">₹ / litre</th>
              <th className="px-3 py-2">Source / note</th><th className="px-3 py-2">Entered by</th>
              {canEdit && <th className="px-3 py-2">Actions</th>}
            </tr></thead>
            <tbody>
              {STATES.map(s => {
                const row = current?.prices?.[s];
                const editing = edit && edit.state === s;
                return (
                  <tr key={s} className="border-t border-gray-100">
                    <td className="px-3 py-1.5 font-medium">{s}</td>
                    {editing ? (
                      <>
                        <td className="px-3 py-1 text-right">
                          <input type="number" step="0.01" className="input w-28 text-right" value={edit.price_per_litre} autoFocus
                                 onChange={e => set('price_per_litre', e.target.value)}
                                 onKeyDown={e => e.key === 'Enter' && saveMut.mutate()}/>
                        </td>
                        <td className="px-3 py-1" colSpan={2}>
                          <input className="input w-full" placeholder="e.g. Purchase mail 16-09-2026" value={edit.source || ''}
                                 onChange={e => set('source', e.target.value)}/>
                        </td>
                        <td className="px-3 py-1 whitespace-nowrap">
                          <button className="btn-primary btn-sm text-xs" disabled={saveMut.isPending} onClick={() => saveMut.mutate()}>Save</button>
                          <button className="p-1 ml-1 text-gray-500" onClick={() => setEdit(null)}><X size={13}/></button>
                        </td>
                      </>
                    ) : (
                      <>
                        <td className="px-3 py-1.5 text-right font-semibold text-[#005ba3]">{row ? nf(row.price) : <span className="text-gray-400 font-normal">not entered</span>}</td>
                        <td className="px-3 py-1.5 text-gray-600">{row?.source || ''}</td>
                        <td className="px-3 py-1.5 text-gray-600">{row?.created_by_name || ''}</td>
                        {canEdit && (
                          <td className="px-3 py-1.5 whitespace-nowrap">
                            {row ? (
                              <>
                                <button className="p-1 text-gray-500 hover:text-blue-600" title="Edit"
                                        onClick={() => setEdit({ id: row.id, state: s, price_per_litre: row.price, source: row.source || '' })}><Pencil size={13}/></button>
                                <button className="p-1 text-gray-500 hover:text-red-600" title="Delete"
                                        onClick={() => window.confirm(`Delete the ${s} diesel price for this fortnight?`) && delMut.mutate(row.id)}><Trash2 size={13}/></button>
                              </>
                            ) : (
                              <button className="btn-secondary btn-sm text-xs flex items-center gap-1"
                                      onClick={() => setEdit({ state: s, price_per_litre: '', source: '' })}><Plus size={12}/> Enter</button>
                            )}
                          </td>
                        )}
                      </>
                    )}
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}

      {/* History grid */}
      <div className="card overflow-hidden">
        <div className="px-4 py-2 font-semibold text-sm border-b border-gray-100">History (₹ / litre by fortnight)</div>
        <div className="overflow-x-auto max-h-[50vh]">
          <table className="w-full text-xs">
            <thead className="sticky top-0 bg-blue-50"><tr className="text-left text-gray-600">
              <th className="px-3 py-2 whitespace-nowrap">Fortnight</th>
              {STATES.map(s => <th key={s} className="px-3 py-2 text-right whitespace-nowrap">{s}</th>)}
            </tr></thead>
            <tbody>
              {isLoading && <tr><td colSpan={5} className="px-3 py-4 text-gray-400">Loading…</td></tr>}
              {!isLoading && !matrix?.periods?.length && <tr><td colSpan={5} className="px-3 py-4 text-gray-400">No diesel prices yet — pick a fortnight above and enter each state's price.</td></tr>}
              {(matrix?.periods || []).map((p, i) => {
                const prev = matrix.periods[i + 1];
                return (
                  <tr key={p.effective_from} className={`border-t border-gray-100 ${p.effective_from === period?.from ? 'bg-yellow-50' : ''}`}>
                    <td className="px-3 py-1.5 whitespace-nowrap">{fmtDate(p.effective_from)} → {fmtDate(p.effective_to)}</td>
                    {STATES.map(s => {
                      const v = p.prices[s]?.price, pv = prev?.prices?.[s]?.price;
                      const d = v != null && pv != null ? v - pv : null;
                      return (
                        <td key={s} className="px-3 py-1.5 text-right whitespace-nowrap">
                          {v == null ? <span className="text-gray-300">—</span> : nf(v)}
                          {d != null && Math.abs(d) >= 0.005 && (
                            <span className={`ml-1 text-[10px] ${d > 0 ? 'text-red-600' : 'text-green-600'}`}>({sign(d)})</span>
                          )}
                        </td>
                      );
                    })}
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>

      {/* Generate preview */}
      {preview && (
        <Modal size="xl" title={`Tanker rates ${fmtDate(preview.effective_from)} → ${fmtDate(preview.effective_to)} from diesel — preview`}
               onClose={() => setPreview(null)}
               footer={
                 <div className="flex flex-wrap items-center gap-3 w-full">
                   {preview.existing > 0 && (
                     <label className="text-xs flex items-center gap-1.5">
                       <input type="checkbox" checked={replace} onChange={e => setReplace(e.target.checked)}/>
                       Replace the {preview.existing} rate row(s) already entered for this fortnight
                     </label>
                   )}
                   <div className="flex-1"/>
                   <button className="btn-secondary text-xs" onClick={() => setPreview(null)}>Cancel</button>
                   <button className="btn-primary text-xs" disabled={genMut.isPending || !preview.generatable}
                           onClick={() => window.confirm(`Write ${preview.generatable} rate row(s) into the Tanker Rate Master for ${fmtDate(preview.effective_from)} → ${fmtDate(preview.effective_to)}?`) && genMut.mutate()}>
                     {genMut.isPending ? 'Saving…' : `Confirm — save ${preview.generatable} rate(s)`}
                   </button>
                 </div>
               }>
          <div className="space-y-3 text-xs">
            <div className="flex flex-wrap gap-4">
              <div>Basis: Tanker Rate Master rows of <b>{fmtDate(preview.previous.from)} → {fmtDate(preview.previous.to)}</b> ({preview.previous_rows} rows)</div>
              {STATES.map(s => {
                const a = preview.diesel_prev[s], b = preview.diesel_new[s];
                return <div key={s}><b>{s.split(' ').map(w => w[0]).join('')}</b> diesel {a == null ? '—' : nf(a)} → {b == null ? <span className="text-red-600">not entered</span> : nf(b)}{a != null && b != null && <span className={Math.abs(b - a) < 0.005 ? 'text-gray-500' : b > a ? 'text-red-600' : 'text-green-600'}> ({Math.abs(b - a) < 0.005 ? 'no change' : sign(b - a)})</span>}</div>;
              })}
            </div>
            {!preview.previous_rows && <div className="text-red-600">No Tanker Rate Master rows for the previous fortnight — enter or upload them first.</div>}
            {preview.existing > 0 && !replace && <div className="text-amber-700">{preview.existing} rate row(s) already exist for this fortnight; they are kept unless you tick Replace.</div>}
            <div className="overflow-auto max-h-[55vh]">
              <table className="w-full text-xs">
                <thead className="sticky top-0 bg-blue-50"><tr className="text-left text-gray-600">
                  {['State', 'Capacity (KL)', 'Transport type', 'Mileage', 'Diesel prev → new', 'Rate prev', 'Rate new', 'Δ', 'Note'].map(h => <th key={h} className="px-2 py-1.5 whitespace-nowrap">{h}</th>)}
                </tr></thead>
                <tbody>
                  {preview.rows.map((r, i) => (
                    <tr key={i} className={`border-t border-gray-100 ${r.new_rate == null ? 'bg-red-50' : r.existing_id && !replace ? 'text-gray-400' : ''}`}>
                      <td className="px-2 py-1">{r.state}</td>
                      <td className="px-2 py-1 text-right">{nf(r.capacity_kl, 1)}</td>
                      <td className="px-2 py-1">{r.transport_type}</td>
                      <td className="px-2 py-1 text-right">{nf(r.mileage_km_per_litre)}</td>
                      <td className="px-2 py-1 text-right whitespace-nowrap">{nf(r.diesel_prev)} → {nf(r.diesel_new)}</td>
                      <td className="px-2 py-1 text-right">{nf(r.prev_rate)}</td>
                      <td className="px-2 py-1 text-right font-semibold text-[#005ba3]">{nf(r.new_rate)}</td>
                      <td className={`px-2 py-1 text-right ${r.delta > 0 ? 'text-red-600' : r.delta < 0 ? 'text-green-600' : ''}`}>{sign(r.delta)}</td>
                      <td className="px-2 py-1 text-gray-600">{r.reason || (r.existing_id ? `exists (${nf(r.existing_rate)})${replace ? ' — will be replaced' : ' — kept'}` : '')}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </Modal>
      )}
    </div>
  );
}
